# Generated by Django 4.1.7 on 2023-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2023-03-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
